services:
  api:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    environment:
      - DB_URL="postgres://${DB_USER}:${DB_PASS}@database:${DB_PORT}/${DB_NAME}"
      - DB_HOST=database
    container_name: payments-api
    ports:
      - 3000:3000
    command: npm run dev
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    container_name: payments-db
    ports:
      - "${DB_PORT}:5432"
