const SHARED = {
  UNKNOWN: "SOMETHING_GONE_WRONG",
};

const USER_CONSTANTS = {
  SUCCESS: {
    CREATE: "USER_CREATED",
  },
  FAILED: {
    CREATE: "FAILED_TO_CREATE_USER",
    FOUND: "USER_NOT_FOUND",
  },
  IN_USE: {
    EMAIL: "EMAIL_IN_USE",
    USERNAME: "USERNAME_IN_USE",
  },
};

const AUTH_CONSTANTS = {
  FAILED: {
    CREDENTIALS: "INVALID_CREDENTIALS",
  },
};

const BALANCE_CONSTANTS = {
  SUCCESS: {
    CREATE: "BALANCE_CREATED",
    UPDATE: "BALANCE_UPDATED",
    DELETE: "BALANCE_DELETED",
  },
  FAILED: {
    CREATE: "FAILED_TO_CREATE_BALANCE",
    UPDATE: "FAILED_TO_UPDATE_BALANCE",
    DELETE: "FAILED_TO_DEELTE_BALANCE",
    FOUND: "BALANCE_NOT_FOUND",
    HAS_PAYMENTS: "CANT_DELETE_BALANCE_WITH_PAYMENTS",
    INSUFICIENT: "INSUFICIENT_BALANCE",
  },
};

const PAYMENT_CONSTANTS = {
  SUCCESS: {
    CREATE: "PAYMENT_CREATED",
    UPDATE: "PAYMENT_UPDATED",
    DELETE: "PAYMENT_DELETED",
  },
  FAILED: {
    FOUND: "PAYMENT_NOT_FOUND",
    CREATE: "FAILED_TO_CREATE_PAYMENT",
    UPDATE: "FAILED_TO_UPDATE_PAYMENT",
    DELETE: "FAILED_TO_DELETE_PAYMENT",
  },
};

export const CONSTANTS = {
  SHARED: SHARED,
  AUTH: AUTH_CONSTANTS,
  USER: USER_CONSTANTS,
  PAYMENT: PAYMENT_CONSTANTS,
  BALANCE: BALANCE_CONSTANTS,
};
